apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: auth
  name: auth
spec:
  ports:
    - name: "7002"
      port: 7002
      targetPort: 7002
  selector:
    io.kompose.service: auth
