apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: data-upload-service
  name: data-upload-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: data-upload-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: data-upload-service
    spec:
      containers:
        - env:
            - name: APP_NAME
              value: brm-data-upload-service
            - name: AUTH_COOKIE_DOMAIN
              value: brm.marutisuzukidataverse.com
            - name: AUTH_COOKIE_SECURE
              value: "true"
            - name: AUTH_FAILURE_REDIRECT_URL
              value: https://brm.marutisuzukidataverse.com/api/auth/sign-in
            - name: AUTH_SUCCESS_REDIRECT_URL
              value: https://brm.marutisuzukidataverse.com
            - name: BRM_S3_AWS_ACCESS_KEY_ID
              value: AKIAW3NPNZRKC7MMG54I
            - name: BRM_S3_AWS_REGION
              value: us-east-1
            - name: BRM_S3_AWS_SECRET_ACCESS_KEY
              value: eeH/A1k31tTEnxUffJozQuaC5RZ8qolC0zBlYKs8
            - name: BRM_S3_BUCKET_NAME
              value: brm-dev-bucket
            - name: JWT_ALGORITHM_FOR_TOKEN
              value: HS256
            - name: JWT_ISSUER
              value: https://brm.marutisuzukidataverse.com/keycloak/realms/brm
            - name: JWT_JWKS_URI
              value: https://brm.marutisuzukidataverse.com/keycloak/realms/brm/protocol/openid-connect/certs
            - name: JWT_SECRET
              value: my_secret
            - name: KEYCLOAK_AUTH_SCOPES
              value: openid email profile
            - name: KEYCLOAK_BASE_URL
              value: https://brm.marutisuzukidataverse.com/keycloak
            - name: KEYCLOAK_CLIENT_ID
              value: brm
            - name: KEYCLOAK_CLIENT_ID_REST
              value: rest-client
            - name: KEYCLOAK_CLIENT_SECRET
              value: cXyIy9JBcAeH6K4rPAHLFGnB5EfCvs7V
            - name: KEYCLOAK_CLIENT_SECRET_REST
              value: qnuIVavwKVKLLK712jlxMKOiKm32YHKk
            - name: KEYCLOAK_GRANT_TYPE
              value: client_credentials
            - name: KEYCLOAK_OIDC_CONNFIG_ENDPOINT
              value: https://brm.marutisuzukidataverse.com/keycloak/realms/brm/.well-known/openid-configuration
            - name: KEYCLOAK_REALM_NAME
              value: brm
            - name: KEYCLOAK_REDIRECT_URI
              value: https://brm.marutisuzukidataverse.com/api/auth/callback
            - name: KEYCLOAK_USERNAME
              value: rest-client
            - name: LOGGER_LOG_LEVEL
              value: debug
            - name: NODE_ENV
              value: production
            - name: OPENAPI_BASE_SCHEMA
              value: dist/api.schema.yml
            - name: PORT
              value: "7007"
            - name: POSTGRES_DATABASE_URL
              value: postgresql://brm_user:brm_password@172.31.96.186:5432/brm
            - name: SERVER_SHUTDOWN_GRACE_PERIOD_MS
              value: "2000"
            - name: SIGNIN_REDIRECT_ALLOWED_HOSTS
              value: brm.marutisuzukidataverse.com,localhost
            - name: WIDGET_SERVICE_PATH
              value: http://widget-service:7003
            - name: WORKFLOW_SERVICE_PATH
              value: http://workflow-service:7008
          image: data-upload-service
          name: brm-data-upload-service
          ports:
            - containerPort: 7007
              protocol: TCP
      restartPolicy: Always
