apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: ADMIN_SERVICE_PATH
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: ADMIN_SERVICE_PATH
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: APP_NAME
            - name: BRM_SERVICE_PATH
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: BRM_SERVICE_PATH
            - name: DATA_UPLOAD_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: DATA_UPLOAD_SERVICE
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: ENVIRONMENT
            - name: LOGIN_API_PATH
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: LOGIN_API_PATH
            - name: LOGOUT_API_PATH
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: LOGOUT_API_PATH
            - name: LOGOUT_REDIRECT_PATH
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: LOGOUT_REDIRECT_PATH
            - name: NOTIFICATION_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: NOTIFICATION_SERVICE
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: PORT_FRONTEND
            - name: REFRESH_API_PATH
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: REFRESH_API_PATH
            - name: USER_INFO_API_PATH
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: USER_INFO_API_PATH
            - name: USER_LIST_API_PATH
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: USER_LIST_API_PATH
            - name: WIDGET_SERVICE_PATH
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: WIDGET_SERVICE_PATH
            - name: WORKFLOW_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: WORKFLOW_SERVICE
          image: frontend
          name: brm-platform-app
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always