apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: keycloak
    spec:
      containers:
        - args:
            - start
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_PASSWORD
              value: brm_password
            - name: KC_DB_URL
              value: jdbc:postgresql://postgres:5432/brm_db
            - name: KC_DB_USERNAME
              value: brm_user
            - name: KC_HOSTNAME
              value: https://brm.marutisuzukidataverse.com/keycloak
            - name: KC_HTTP_RELATIVE_PATH
              value: /keycloak
            - name: KC_PROXY
              value: edge
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: Us!ngBRM
          image: keycloak/keycloak:26.0
          name: brm-keycloak
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/localtime
              name: keycloak-cm0
              readOnly: true
              subPath: localtime
            - mountPath: /opt/keycloak/themes/brm
              name: keycloak-claim1
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: localtime
                path: localtime
            name: keycloak-cm0
          name: keycloak-cm0
        - name: keycloak-claim1
          persistentVolumeClaim:
            claimName: keycloak-claim1
