apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: keycloak
    spec:
      containers:
        - args:
            - start
          env:
            - name: KC_DB
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_DB
            - name: KC_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_DB_PASSWORD
            - name: KC_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_DB_URL
            - name: KC_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_DB_USERNAME
            - name: KC_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_HOSTNAME
            - name: KC_HTTP_RELATIVE_PATH
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_HTTP_RELATIVE_PATH
            - name: KC_PROXY
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_PROXY
            - name: KEYCLOAK_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_ADMIN_USERNAME
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_ADMIN_PASSWORD
          image: keycloak/keycloak:{{ .Values.keycloak.image.tag }}
          imagePullPolicy: IfNotPresent
          name: brm-keycloak
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/localtime
              name: keycloak-cm0
              readOnly: true
              subPath: localtime
            - mountPath: /opt/keycloak/themes/brm
              name: keycloak-claim1
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: localtime
                path: localtime
            name: keycloak-cm0
          name: keycloak-cm0
        - name: keycloak-claim1
          persistentVolumeClaim:
            claimName: keycloak-claim1