apiVersion: v1
kind: Service
metadata:
 name: brm-internal-nlb
 annotations:
service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
service.beta.kubernetes.io/aws-load-balancer-internal: "true"
 labels:
   app: brm-nlb
spec:
 type: LoadBalancer
 selector:
   app: brm-nlb
 ports:
   - protocol: TCP
     port: 80
     targetPort: 80
   - protocol: TCP
     port: 443
     targetPort: 443
