apiVersion: apps/v1
kind: Deployment
metadata:
 name: microservice-2
 labels:
   app: microservice-2
spec:
 replicas: 1
 selector:
   matchLabels:
     app: microservice-2
 template:
   metadata:
     labels:
       app: microservice-2
   spec:
     containers:
       - name: microservice-2
         image: nginx:latest
         ports:
           - containerPort: 7003
         volumeMounts:
           - name: nginx-config
             mountPath: /etc/nginx/nginx.conf
             subPath: nginx.conf
       volumes:
         - name: nginx-config
           configMap:
             name: custom-nginx-config
        
---
apiVersion: v1
kind: Service
metadata:
 name: microservice-2
 labels:
   app: microservice-2
spec:
 type: ClusterIP
 selector:
   app: microservice-2
 ports:
   - protocol: TCP
     port: 80
     targetPort: 7003
