apiVersion: apps/v1
kind: Deployment
metadata:
 name: microservice-2
 labels:
   app: microservice-2
spec:
 replicas: 1
 selector:
   matchLabels:
     app: microservice-2
 template:
   metadata:
     labels:
       app: microservice-2
   spec:
     containers:
       - name: microservice-2
         image: nginx:latest
         ports:
           - containerPort: 7002
---
apiVersion: v1
kind: Service
metadata:
 name: microservice-2
 labels:
   app: microservice-2
spec:
 type: ClusterIP
 selector:
   app: microservice-2
 ports:
   - protocol: TCP
     port: 80
     targetPort: 7002
