apiVersion: apps/v1
kind: Deployment
metadata:
 name: microservice-1
 labels:
   app: microservice-1
spec:
 replicas: 1
 selector:
   matchLabels:
     app: microservice-1
 template:
   metadata:
     labels:
       app: microservice-1
   spec:
     containers:
       - name: microservice-1
         image: nginx:latest
         ports:
           - containerPort: 7001
---
apiVersion: v1
kind: Service
metadata:
 name: microservice-1
 labels:
   app: microservice-1
spec:
 type: ClusterIP
 selector:
   app: microservice-1
 ports:
   - protocol: TCP
     port: 80
     targetPort: 7001
