apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internal-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: aacf4f2dd928f4d9992dbb52e81cd52b-93330db5da882f80.elb.ap-south-1.amazonaws.com
    http:
      paths:
      - path: /service1
        pathType: Prefix
        backend:
          service:
            name: microservice-1
            port:
              number: 80
      - path: /service2
        pathType: Prefix
        backend:
          service:
            name: microservice-2
            port:
              number: 80
