apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: workflow-service
  name: workflow-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: workflow-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: workflow-service
    spec:
      containers:
        - env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: WORKFLOW_SERVICE_APP_NAME
            - name: AUTH_COOKIE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: AUTH_COOKIE_DOMAIN
            - name: AUTH_COOKIE_SECURE
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: AUTH_COOKIE_SECURE
            - name: AUTH_FAILURE_REDIRECT_URL
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: AUTH_FAILURE_REDIRECT_URL
            - name: AUTH_SUCCESS_REDIRECT_URL
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: AUTH_SUCCESS_REDIRECT_URL
            - name: JWT_ALGORITHM_FOR_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: JWT_ALGORITHM_FOR_TOKEN
            - name: JWT_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: JWT_ISSUER
            - name: JWT_JWKS_URI
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: JWT_JWKS_URI
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: JWT_SECRET
            - name: KEYCLOAK_AUTH_SCOPES
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_AUTH_SCOPES
            - name: KEYCLOAK_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_BASE_URL
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_CLIENT_ID
            - name: KEYCLOAK_CLIENT_ID_REST
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_CLIENT_ID_REST
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_CLIENT_SECRET
            - name: KEYCLOAK_CLIENT_SECRET_REST
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_CLIENT_SECRET_REST
            - name: KEYCLOAK_GRANT_TYPE
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_GRANT_TYPE
            - name: KEYCLOAK_OIDC_CONNFIG_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_OIDC_CONNFIG_ENDPOINT
            - name: KEYCLOAK_REALM_NAME
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_REALM_NAME
            - name: KEYCLOAK_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_REDIRECT_URI
            - name: KEYCLOAK_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: KEYCLOAK_USERNAME
            - name: LOGGER_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: LOGGER_LOG_LEVEL
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: NODE_ENV
            - name: OPENAPI_BASE_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: OPENAPI_BASE_SCHEMA
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: WORKFLOW_SERVICE_PORT
            - name: POSTGRES_DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: POSTGRES_DATABASE_URL
            - name: SERVER_SHUTDOWN_GRACE_PERIOD_MS
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: SERVER_SHUTDOWN_GRACE_PERIOD_MS
            - name: SIGNIN_REDIRECT_ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: brm-env-config
                  key: SIGNIN_REDIRECT_ALLOWED_HOSTS
          image: workflow-service
          name: brm-workflow-service
          ports:
            - containerPort: 7008
              protocol: TCP
      restartPolicy: Always